# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66fdfc63354b70208f1a4daf9a042dfff6515599cf33d79428067d78f58d22c2ae1a5497d561caaace271613752f41f8e7cbf2520c3a5c34d9b1f34b08a9f174

test:
  secret_key_base: 3bef1b5f0f289e485ba86e24e784d256e5f8de2026639cea6c9a22b280fe203c2092e665385c19c4bb9902313859417dc76e9019414ec748c8e24c6c27dd5922

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
